site_name: Caesb

theme:
  name: material
  icon:
    repo: fontawesome/brands/git-alt
  palette:
    - scheme: default 
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: #191717
      accent: #8ECDDD
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: #191717
      accent: #8ECDDD
  font:
    text: Roboto
  language: pt
  features:
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - navigation.tabs.sticky

nav:
  - Início: index.md
  - Planejamento:
      - Heatmap: heatmap/heatmap.md
      - Metodologia: planejamento/metodologia.md
      - Ferramentas: planejamento/ferramentas.md
      - Processo Design: planejamento/processoDesign.md
      - Cronograma: planejamento/cronograma.md
      - Cronograma executado: planejamento/cronograma_exec.md
      - Lista de Sites Avaliados: planejamento/SitesAvaliados.md
  - Análise de Requisitos:
      - Aspectos Éticos: analise-de-requisitos/aspectos-eticos.md
      - Perfil do Usuário: analise-de-requisitos/perfil-do-usuario.md
      - Personas: analise-de-requisitos/Personas.md
      - Cenários: analise-de-requisitos/cenario1.md
      - Guia de estilo: analise-de-requisitos/guia-de-estilo.md
      - Caracteristicas: analise-de-requisitos/caracteristicas.md
      - Análise de Tarefas: 
          - Análise Hierarquica de Tarefas: analise-de-requisitos/analise-de-tarefas/HTA.md
          - GOMS: analise-de-requisitos/analise-de-tarefas/GOMS.md
      - Princípios Gerais do Projeto: analise-de-requisitos/principios_gerais.md
      - Metas de Usabilidade: analise-de-requisitos/metas-usabilidade.md
  - Design, Avaliação e Desenvolvimento:
      - Nivel 1:
          - Analise de tarefas: 
              - Planejamento da avaliação da analise de tarefas: design, avaliação e desenvolvimento/Planejamento da avaliação.md
              - Planejamento do relato dos resultados da avaliação da análise de tarefas: des-aval-des/plan-rel-res.md
              - Relato dos resultados: design, avaliação e desenvolvimento/Relato dos resultados.md
          - Storyboard: 
              - Planejamento da Avaliação do Storyboard: design, avaliação e desenvolvimento/Planejamento-Avaliação-Storyboard.md
              - Planejamento do relato dos resultados do storyboard: design-avaliacao-desenv/nivel1/storyboard/planej-resultado-story.md
              - Relato dos resultados: design, avaliação e desenvolvimento/Relato dos resultados do story.md
              - Storyboards: design, avaliação e desenvolvimento/Storyboards.md
      - Nivel 2:
          - protótipo de Papel:
              - Planejamento da Avaliação do Protótipo de Papel: design, avaliação e desenvolvimento/planejamento-prototipo-papel.md
              - Planejamento do Relato dos Resultados do Protótipo de papel: design, avaliação e desenvolvimento/planejamento_do_relato_dos_resultados_papel.md
              - Relato dos Resultados do Protótipo de papel: design, avaliação e desenvolvimento/Relato_resultados_prototipo.md
      - Nivel 3:
          - Protótipo de alta fidelidade:
              - Planejamento da avaliação do protótipo de alta fidelidade: design, avaliação e desenvolvimento/nivel3/planejamento-da-avaliacao-prototipo-alta.md
              - Planejamento do relato dos resultados do protótipo de alta fidelidade: design, avaliação e desenvolvimento/nivel3/planejamento-do-relato-result-prototipo-alta.md
              - Relato dos resultados do Protótipo de alta fidelidade: design, avaliação e desenvolvimento/nivel3/relato-resultados-prototipo-alta.md
  - Verificação:
      - Grupo 06:
        - Etapa 3:
              - Planejamento: verificacao/grupo6/etapa3/planejamento.md
              - Metas de Usabilidade: verificacao/grupo6/etapa3/guia_estilo.md
              - Características: verificacao/grupo6/etapa3/caracteristica-plataforma.md
              - Guia Estilo: verificacao/grupo6/etapa3/guia_estilo.md
        - Etapa 08:
              - Relato da Avaliação do Protótipo de Alta Fidelidade: verificacao/grupo6/etapa8/relato-prototipo-alta.md
      - Grupo 07:
        - Etapa 1:
              - Planejamento: verificacao/Etapa1/planejamento.md
              - Verificação Equipe: verificacao/Etapa1/equipe.md
              - Verificação de Ferramentas: verificacao/Etapa1/ferramentas.md
              - Verificação do Cronograma: verificacao/Etapa1/cronograma.md
              - Verificação dos sites avaliados: verificacao/Etapa1/sites-avaliados.md
              - Verificação do site escolhido: verificacao/Etapa1/site-escolhido.md
              - Verificação do Processo de design: verificacao/Etapa1/processo-design.md 
        - Etapa 2:
              - Verificação do Planejamento: verificacao/Etapa2/planejamento.md
              - Verificação dos Aspectos Éticos: verificacao/Etapa2/aspectos_eticos.md
              - Verificação do Perfil de Usuário: verificacao/Etapa2/perfil_de_usuario.md
              - Verificação dos Cenários: verificacao/Etapa2/cenarios.md
              - Verificação das Personas: verificacao/Etapa2/personas.md
              - Verificação da Análise de Tarefas: verificacao/Etapa2/analise_de_tarefas.md
        - Etapa 3:
              - Planejamento: verificacao/Etapa3/planejamento.md
              - Verificação Princípios Gerais: verificacao/Etapa3/principios-gerais.md
              - Verificação Metas de Usabilidade: verificacao/Etapa3/metas-usabilidade.md
              - Verificação Guia de Estilo: verificacao/Etapa3/guia_estilo.md
              - Verificação Característica da Plataforma: verificacao/Etapa3/caracteristica-plataforma.md
        - Etapa 4:
              - Planejamento: verificacao/Etapa4/planejamento.md
              - Verificacao do Planejamento de Storyboard: verificacao/Etapa4/planej-avalia-storyboard.md
              - Verificacao do Relato dos Resultados do Storyboard: verificacao/Etapa4/planej-relato-resultados-storyboard.md
              - Verificação do Storyboard: verificacao/Etapa4/storyboards.md
              - Verificação do Planejamento da Análise de Tarefas: verificacao/Etapa4/planej-avalia-analise-tarefas.md
              - Verificação da Relato dos Resultados da Análise de Tarefas: verificacao/Etapa4/planej-relato-resultados-analise-tarefas.md
        - Etapa 5:
              - Planejamento: verificacao/Etapa5/planejamento.md
              - Verificação do relato dos resultados da analise de tarefas: verificacao/Etapa5/relato-tarefas.md
              - Verificação do relato dos resultados do storyboard: verificacao/Etapa5/relato-story.md
              - Verificação do planejamento do protótipo de papel: verificacao/Etapa5/planej-prototipo-papel.md
              - Verificação do planejamento do relato dos resultados do protótipo de papel: verificacao/Etapa5/planej-relato-resultados-prototipo-papel.md
        
  - Atas das Reuniões:
      - Reunião 1 - 26/09/2023: atas-das-reunioes/reuniao1.md
      - Reunião 2 - 04/10/2023: atas-das-reunioes/reuniao2.md
      - Reunião 3 - 08/10/2023: atas-das-reunioes/reuniao3.md
      - Reunião 4 - 09/10/2023: atas-das-reunioes/reuniao4.md
      - Reunião 5 - 11/10/2023: atas-das-reunioes/reuniao5.md
      - Reunião 6 - 17/10/2023: atas-das-reunioes/reuniao6.md
      - Reunião 7 - 21/10/2023: atas-das-reunioes/reuniao7.md
  - Apresentações:
      - Entregas: apresentacoes/Entregas.md
  - Site selecionado:
    - Site escolhido: site-escolhido/siteEscolhido.md
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji
  - pymdownx.tasklist
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences




