site_name: Caesb

theme:
  name: material
  icon:
    repo: fontawesome/brands/git-alt
  palette:
    - scheme: default 
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: #191717
      accent: #8ECDDD
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: #191717
      accent: #8ECDDD
  font:
    text: Roboto
  language: pt
  features:
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - navigation.tabs.sticky

nav:
  - Início: index.md
  - Planejamento:
      - Heatmap: heatmap/heatmap.md
      - Metodologia: planejamento/metodologia.md
      - Ferramentas: planejamento/ferramentas.md
      - Processo Design: planejamento/processoDesign.md
      - Cronograma: planejamento/cronograma.md
      - Cronograma executado: planejamento/cronograma_exec.md
      - Lista de Sites Avaliados: planejamento/SitesAvaliados.md
  - Análise de Requisitos:
      - Aspectos Éticos: analise-de-requisitos/aspectos-eticos.md
      - Perfil do Usuário: analise-de-requisitos/perfil-do-usuario.md
      - Personas: analise-de-requisitos/Personas.md
      - Cenários: analise-de-requisitos/cenario1.md
      - Guia de estilo: analise-de-requisitos/guia-de-estilo.md
      - Caracteristicas: analise-de-requisitos/caracteristicas.md
      - Análise de Tarefas: 
          - Análise Hierarquica de Tarefas: analise-de-requisitos/analise-de-tarefas/HTA.md
          - GOMS: analise-de-requisitos/analise-de-tarefas/GOMS.md
      - Princípios Gerais do Projeto: analise-de-requisitos/principios_gerais.md
      - Metas de Usabilidade: analise-de-requisitos/metas-usabilidade.md
  - Design, Avaliação e Desenvolvimento:
      - Planejamento do relato dos resultados da avaliação da análise de tarefas: des-aval-des/plan-rel-res.md
      - Planejamento da avaliação da analise de tarefas: design, avaliação e desenvolvimento/Planejamento da avaliação.md
  - Atas das Reuniões:
      - Reunião 1 - 26/09/2023: atas-das-reunioes/reuniao1.md
      - Reunião 2 - 04/10/2023: atas-das-reunioes/reuniao2.md
      - Reunião 3 - 08/10/2023: atas-das-reunioes/reuniao3.md
      - Reunião 4 - 09/10/2023: atas-das-reunioes/reuniao4.md
      - Reunião 5 - 11/10/2023: atas-das-reunioes/reuniao5.md
      - Reunião 6 - 17/10/2023: atas-das-reunioes/reuniao6.md
      - Reunião 7 - 21/10/2023: atas-das-reunioes/reuniao7.md
  - Apresentações:
      - Entregas: apresentacoes/Entregas.md
  - Site selecionado:
    - Site escolhido: site-escolhido/siteEscolhido.md
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji
  - pymdownx.tasklist
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences




